//
//  String.h
//  Order
//
//  Created by koji kodama on 13/05/25.
//  Copyright (c) 2013年 koji kodama. All rights reserved.
//

#import <Foundation/Foundation.h>

@interface String : NSObject


+ (NSString*)Order_Station;
+ (NSString*)Cancel1;
+ (NSString*)Clear_this_slip;
+ (NSString*)Input_the_table;
+ (NSString*)The_Table_which;
+ (NSString*)The_number;
+ (NSString*)Order_send;
+ (NSString*)Table_status_did_not;
+ (NSString*)Table_did_not_select;
+ (NSString*)Split_Table_for_New_Customer;
+ (NSString*)Slip_has_been_printed;
+ (NSString*)Table_is_empty;
+ (NSString*)No_order1;
+ (NSString*)Choice_staff;
+ (NSString*)New_or_Add;
+ (NSString*)No_order2;
+ (NSString*)No_canceled;
+ (NSString*)No_canceled_date;
+ (NSString*)Cannot_be_divide1;
+ (NSString*)Cannot_be_divide2;
+ (NSString*)Divide_Execute;
+ (NSString*)Choose;
+ (NSString*)Divide_Execute_some;
+ (NSString*)Can_be_divided;
+ (NSString*)Print_Slip;
+ (NSString*)Input_num;
+ (NSString*)The_number_of_the_composition;
+ (NSString*)Cancel_syohin;
+ (NSString*)Password;
+ (NSString*)Wrong_password;
+ (NSString*)Setting_cancel;
+ (NSString*)figure;
+ (NSString*)To_figure;
+ (NSString*)Entry_to;
+ (NSString*)Entry;
+ (NSString*)System_will_finish;
+ (NSString*)Load_Master_with_num;
+ (NSString*)Set_up;
+ (NSString*)Load_Master;
+ (NSString*)Clear_table;
+ (NSString*)Kept_already;
+ (NSString*)Clear_table2;
+ (NSString*)Vacant;
+ (NSString*)Reserve;
+ (NSString*)Choose_split;
+ (NSString*)not_possible_to_confirm;
+ (NSString*)Plese_try_again;
+ (NSString*)Network_is_disconnected;
+ (NSString*)search;
+ (NSString*)searchC;
+ (NSString*)searchAdd;
+ (NSString*)searchCheck;
+ (NSString*)searchCancel;
+ (NSString*)tableNew;
+ (NSString*)tableAdd;
+ (NSString*)tableOrder;
+ (NSString*)tableCancel;
+ (NSString*)tableConfirm;
+ (NSString*)tableDivide;
+ (NSString*)tableMove1;
+ (NSString*)tableMove2;
+ (NSString*)tableNo;
+ (NSString*)tableCook;
+ (NSString*)table;
+ (NSString*)slipNo;
+ (NSString*)Search;
+ (NSString*)Printing_slip;
+ (NSString*)Indicate_on_display;
+ (NSString*)The_change;
+ (NSString*)Change_setting;
+ (NSString*)Yes;
+ (NSString*)No;
+ (NSString*)Sub_menu;
+ (NSString*)Setting_system;
+ (NSString*)Layer;
+ (NSString*)Input_the_number;
+ (NSString*)Deal;
+ (NSString*)Clear_Message;
+ (NSString*)Speak_now;
+ (NSString*)Tray;
+ (NSString*)Add_to_trays;
+ (NSString*)DeviceID;
+ (NSString*)Menu_pattern;
+ (NSString*)Erase_Tray;
+ (NSString*)Clear_This_Item;
+ (NSString*)Clear_This_Menu;
+ (NSString*)Extra_time;
+ (NSString*)EXTRA_TIME_OF_TABLE;
+ (NSString*)HOUR;
+ (NSString*)MINITES1;
+ (NSString*)MINITES2;
+ (NSString*)RESET;
+ (NSString*)SUBMIT;
+ (NSString*)CANCEL2;
+ (NSString*)The_content;
+ (NSString*)It_changes;
+ (NSString*)SCHEDULE_TIME;
+ (NSString*)EXTRA_TIME;
+ (NSString*)NEW_TIME;
+ (NSString*)Order_;
+ (NSString*)Enter_a_message;


+ (NSString*)Ver;
+ (NSString*)Setting;
+ (NSString*)Program_end;
+ (NSString*)Download;
+ (NSString*)Normal;
+ (NSString*)Select_staff;
//2015-11-04 ueda
+ (NSString*)No_Staff;
+ (NSString*)Served_already;
+ (NSString*)Str_t;
+ (NSString*)Cancel_confirm;
+ (NSString*)Confirm;
+ (NSString*)Total;
+ (NSString*)Stock;
+ (NSString*)Out_of_stock_change;
+ (NSString*)Go_to_modify;
+ (NSString*)Demo_mode;
+ (NSString*)Training_mode;
+ (NSString*)Show_slip;
+ (NSString*)No_amount;
+ (NSString*)Reissue_slip;
+ (NSString*)Reissue_slip2;
+ (NSString*)ONLY;
+ (NSString*)ALL;
+ (NSString*)Cancel_slip;
+ (NSString*)CHECK_OUT;
+ (NSString*)TICKET;
+ (NSString*)CHOICE;


+ (NSString*)bt_divide;
+ (NSString*)bt_move;
+ (NSString*)bt_cook;
+ (NSString*)bt_setting;
+ (NSString*)bt_check;
+ (NSString*)bt_cancel;
+ (NSString*)bt_add;
+ (NSString*)bt_new;
+ (NSString*)bt_next;
+ (NSString*)bt_return;
+ (NSString*)bt_search;
+ (NSString*)bt_send;
+ (NSString*)bt_confirm;
+ (NSString*)bt_done;
+ (NSString*)bt_count;
+ (NSString*)bt_finish;
+ (NSString*)bt_print1;
+ (NSString*)bt_print2;
+ (NSString*)bt_print3;
+ (NSString*)bt_order;
+ (NSString*)bt_ok;
+ (NSString*)bt_top;

+ (NSString*)bt_sort;
+ (NSString*)bt_addOrder;

+ (NSString*)man;
+ (NSString*)woman;
//2014-10-24 ueda
+ (NSString*)manTypeC;
+ (NSString*)womanTypeC;
+ (NSString*)childTypeC;

+ (NSString*)The_change_of_the_setting;
+ (NSString*)Changes_setting;


+ (NSString*)TerminalID;
+ (NSString*)HostIP;
//2014-08-01 ueda
+ (NSString*)PortNoStr;
+ (NSString*)Time_out;
+ (NSString*)Entry_Type;
+ (NSString*)Slip_request_type;
+ (NSString*)Slip_No;
+ (NSString*)Details;
+ (NSString*)Newes;
+ (NSString*)Non_selection_menu;
+ (NSString*)Sound_effect;
+ (NSString*)Transceiver;
+ (NSString*)On;
+ (NSString*)Off;
+ (NSString*)Fixation_of_checkout;
+ (NSString*)On2;
+ (NSString*)Off2;
+ (NSString*)Checkout_slip_output;
+ (NSString*)Table_input_type;
+ (NSString*)Select;
+ (NSString*)Input;
+ (NSString*)Order_code_input;
+ (NSString*)Off3;
+ (NSString*)On3;
+ (NSString*)Regular_Category;
+ (NSString*)Input_SP;
+ (NSString*)Modify;
+ (NSString*)Modify2;
+ (NSString*)Off4;
+ (NSString*)QTY;
+ (NSString*)Search_key;
+ (NSString*)Menu_list;
+ (NSString*)On5;
+ (NSString*)Off5;
+ (NSString*)Menu_list_pattern;
+ (NSString*)SectionCD;
+ (NSString*)Divide_type;
+ (NSString*)Divide10;
+ (NSString*)Divide2;
+ (NSString*)Input_SP2;
+ (NSString*)VLayer;
+ (NSString*)Customer;
+ (NSString*)Cooking_instruction;
+ (NSString*)Training;
+ (NSString*)Off6;
+ (NSString*)On6;
+ (NSString*)Language;
+ (NSString*)Japanese;
+ (NSString*)English;
+ (NSString*)Currency;
+ (NSString*)Yen;
+ (NSString*)Dollar;
+ (NSString*)Demo;
+ (NSString*)Ftp_user;
+ (NSString*)Ftp_password;
//2014-06-23 ueda
+ (NSString*)PhotoMsg;
//2014-08-05 ueda
+ (NSString*)scanBarcodeMsg;
+ (NSString*)Cancel3;
//2014-08-19 ueda
+ (NSString*)useBarcodeMsg;
//2014-09-05 ueda
+ (NSString*)typeCseatCaptionType;
+ (NSString*)typeCseatCaptionAlphabet;
+ (NSString*)typeCseatCaptionNumber;
+ (NSString*)typeCseatAndOrdertypeTitle;
//2014-09-16 ueda
+ (NSString*)Enter_a_Arrange;
//2014-09-19 ueda
+ (NSString*)Cut_Character;
//2014-10-02 ueda
+ (NSString*)Arrange_Comment;
//2014-10-28 ueda
+ (NSString*)transitionStr;
+ (NSString*)scrollStr;
//2014-10-28 ueda
+ (NSString*)sendOrderRetry;
//2014-10-30 ueda
+ (NSString*)home_back;
//2014-12-04 ueda
+ (NSString*)Cannot_connect;
//2014-12-12 ueda
+ (NSString*)childInputStr;
//2015-02-04 ueda
+ (NSString*)Delete_Called;
//2015-03-24 ueda
+ (NSString*)RegisterType;
+ (NSString*)SimpleRegi;
+ (NSString*)PokeRegi;
+ (NSString*)PokeRegiOnly;
+ (NSString*)PaymentType;
+ (NSString*)PayNormal;
+ (NSString*)PayYadokake;
+ (NSString*)bt_register;
+ (NSString*)bt_checkOut;
+ (NSString*)PayTitleTotal;
+ (NSString*)PayTitleCash;
+ (NSString*)PayTitleCard;
+ (NSString*)PayTitleChange;
+ (NSString*)PayTitleRyosyusyo;
+ (NSString*)PayTitleCustomer;
+ (NSString*)PayTitleCustomerName;
+ (NSString*)urikake1Error;
+ (NSString*)PokeRegiCancel;
//2015-04-14 ueda
+ (NSString*)tableMultiSelectTitle;
+ (NSString*)tableMultiSelectOkTitle;
+ (NSString*)tableMultiSelectNgTitle;
//2015-04-16 ueda
+ (NSString*)AddOrderConfirm;
//2015-04-20 ueda
+ (NSString*)staffCodeInputTitle;
+ (NSString*)searchStaffCode;
+ (NSString*)staffCodeNotFound;
//2015-06-01 ueda
+ (NSString*)useOrderStatusTitle;
+ (NSString*)useOrderStatusNotTitle;
+ (NSString*)useOrderStatusYesTitle;
+ (NSString*)Select_Printer;
//2015-06-02 ueda
+ (NSString*)TellCall;
//2015-06-17 ueda
+ (NSString*)staffCodeKetaTitle;
+ (NSString*)staffCodeKeta6;
+ (NSString*)staffCodeKeta2;
//2015-09-17 ueda
+ (NSString*)useOrderConfirmTitle;
+ (NSString*)useOrderConfirmNotTitle;
+ (NSString*)useOrderConfirmYesTitle;
//2016-02-03 ueda ASTERISK
+ (NSString*)bt_nextPage;
+ (NSString*)bt_prevPage;

@end
